# -*- coding: utf-8 -*-
"""gen ai mathematic model - streamlit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvx1L7VwAWTZ-D8EDzd58OUgiOcgbZq2
"""

import streamlit as st
import sympy as sp
import numpy as np
from scipy.fft import fft
from scipy.integrate import quad
from sympy import Matrix, symbols, diff, integrate, laplace_transform

st.set_page_config(page_title="Advanced Math Solver", layout="wide")

st.title("🧠 Advanced Mathematical Solver (Research Grade)")
st.caption("Symbolic + Numerical | Auditable | PhD-Level")

# ------------------------
# Utility
# ------------------------
def parse_expr(expr):
    try:
        return sp.sympify(expr)
    except Exception as e:
        st.error(f"Invalid expression: {e}")
        return None

def parse_vector(text):
    try:
        return np.array(list(map(float, text.split(","))))
    except:
        st.error("Vector must be comma-separated numbers.")
        return None

# ------------------------
# Sidebar
# ------------------------
domain = st.sidebar.selectbox(
    "Select Mathematical Domain",
    [
        "Arithmetic / Algebra",
        "Linear Algebra",
        "Calculus",
        "Transforms (FFT / Laplace)",
        "Vector Calculus (Maxwell)"
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown("**Design philosophy:** Deterministic, modular, explainable")

# ========================
# 1️⃣ Arithmetic / Algebra
# ========================
if domain == "Arithmetic / Algebra":
    st.subheader("Arithmetic / Algebra")

    expr = st.text_input("Enter expression (e.g. (x+1)^3 - x^3):")
    var = st.text_input("Variable (optional):", value="x")

    if st.button("Solve"):
        e = parse_expr(expr)
        if e:
            x = symbols(var)
            st.write("### Cell-wise Results")
            st.write("Expression:", e)
            st.write("Expanded:", sp.expand(e))
            st.write("Simplified:", sp.simplify(e))
            st.write("Derivative:", diff(e, x))
            st.write("Integral:", integrate(e, x))

# ========================
# 2️⃣ Linear Algebra
# ========================
elif domain == "Linear Algebra":
    st.subheader("Linear Algebra")

    v1 = st.text_input("Vector X (comma-separated):", "1,2,3")
    v2 = st.text_input("Vector Y (comma-separated):", "4,5,6")

    if st.button("Compute"):
        x = parse_vector(v1)
        y = parse_vector(v2)

        if x is not None and y is not None:
            st.write("### Cell-wise Results")
            st.write("Dot Product:", np.dot(x, y))
            st.write("Norm X:", np.linalg.norm(x))
            st.write("Norm Y:", np.linalg.norm(y))
            st.write("Cosine Similarity:",
                     np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y)))

# ========================
# 3️⃣ Calculus (PhD level)
# ========================
elif domain == "Calculus":
    st.subheader("Calculus")

    expr = st.text_input("Function f(x):", "x^3 * exp(-x)")
    var = st.text_input("Variable:", "x")

    if st.button("Analyze"):
        f = parse_expr(expr)
        if f:
            x = symbols(var)

            st.write("### Cell-wise Results")
            st.write("f(x):", f)
            st.write("First Derivative:", diff(f, x))
            st.write("Second Derivative:", diff(f, x, 2))
            st.write("Indefinite Integral:", integrate(f, x))

            # Numerical integration
            fn = sp.lambdify(x, f, "numpy")
            val, err = quad(fn, 0, 10)
            st.write("∫₀¹⁰ f(x) dx (numerical):", val)
            st.write("Error estimate:", err)

# ========================
# 4️⃣ Transforms
# ========================
elif domain == "Transforms (FFT / Laplace)":
    st.subheader("Transforms")

    transform_type = st.selectbox("Select Transform", ["FFT", "Laplace"])

    if transform_type == "FFT":
        signal = st.text_input("Signal (comma-separated):", "1,0,1,0")

        if st.button("Compute FFT"):
            s = parse_vector(signal)
            if s is not None:
                F = fft(s)
                st.write("### Cell-wise Results")
                st.write("Signal:", s)
                st.write("FFT:", F)
                st.write("Magnitude:", np.abs(F))

    else:
        expr = st.text_input("Function f(t):", "sin(t)")
        if st.button("Compute Laplace"):
            t, s = symbols("t s")
            f = parse_expr(expr)
            if f:
                L = laplace_transform(f, t, s, noconds=True)
                st.write("### Cell-wise Results")
                st.write("f(t):", f)
                st.write("Laplace Transform:", L)

# ========================
# 5️⃣ Vector Calculus (Maxwell)
# ========================
elif domain == "Vector Calculus (Maxwell)":
    st.subheader("Vector Calculus")

    Fx = st.text_input("Fx(x,y,z):", "x*y")
    Fy = st.text_input("Fy(x,y,z):", "y*z")
    Fz = st.text_input("Fz(x,y,z):", "z*x")

    if st.button("Compute"):
        x, y, z = symbols("x y z")
        Fx_e = parse_expr(Fx)
        Fy_e = parse_expr(Fy)
        Fz_e = parse_expr(Fz)

        if Fx_e and Fy_e and Fz_e:
            divergence = diff(Fx_e, x) + diff(Fy_e, y) + diff(Fz_e, z)
            curl = Matrix([
                diff(Fz_e, y) - diff(Fy_e, z),
                diff(Fx_e, z) - diff(Fz_e, x),
                diff(Fy_e, x) - diff(Fx_e, y)
            ])

            st.write("### Cell-wise Results")
            st.write("Divergence ∇·F:", divergence)
            st.write("Curl ∇×F:", curl)